export const THREAD_MESSAGES_WINDOW_SIZE = 2_000;
export const THREAD_CHECKPOINTS_WINDOW_SIZE = 500;
export const THREAD_PROPOSED_PLANS_WINDOW_SIZE = 200;
export const THREAD_ACTIVITIES_WINDOW_SIZE = 500;

export const ORCHESTRATION_REPLAY_BATCH_SIZE = 500;
